/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Udec.co;
import Clases.Abrir_excel;
import Clases.Abrir_opera;
import Clases.Fecha_hora;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;



/**
 *
 * @author Jonathan Arevalo
 */
public class Cosmos extends javax.swing.JFrame {
    
        Fecha_hora fechaHora = new Fecha_hora();
        String user="Jonathan";
        String pass="Arevalo1501*";
        public Cosmos() {
        initComponents();
        Menu.setVisible(false);
        mostrar_fecha();
        ajustarImagen(Logo);
        ajustarImagen(Fondo_Login);
        ajustarImagen(Fondo_Escritorio);
        ajustarImagen(PAPELERA);
        ajustarImagen(OPERA);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        PInicio = new javax.swing.JPanel();
        inicio = new javax.swing.JLabel();
        PUsuario = new javax.swing.JPanel();
        ejemplo = new javax.swing.JTextField();
        PContraseña = new javax.swing.JPanel();
        ejemplocontraseña = new javax.swing.JPasswordField();
        PBoton = new javax.swing.JPanel();
        boton = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        DatosNo = new javax.swing.JLabel();
        PLogo = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Fondo_Login = new javax.swing.JLabel();
        Escritorio = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        OPERA = new javax.swing.JLabel();
        PAPELERA = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Barra_Tareas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FECHA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HORA = new javax.swing.JLabel();
        Fondo_Escritorio = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PInicio.setBackground(new java.awt.Color(255, 255, 255));
        PInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        inicio.setText("Iniciar Sesión");
        PInicio.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 119, 36));

        PUsuario.setBackground(new java.awt.Color(243, 244, 246));

        ejemplo.setBackground(new java.awt.Color(243, 244, 246));
        ejemplo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ejemplo.setForeground(new java.awt.Color(204, 204, 204));
        ejemplo.setText("ejemplo.gmail.com");
        ejemplo.setBorder(null);
        ejemplo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ejemploMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ejemploMousePressed(evt);
            }
        });
        ejemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemploActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PUsuarioLayout = new javax.swing.GroupLayout(PUsuario);
        PUsuario.setLayout(PUsuarioLayout);
        PUsuarioLayout.setHorizontalGroup(
            PUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ejemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        PUsuarioLayout.setVerticalGroup(
            PUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ejemplo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        PInicio.add(PUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        PContraseña.setBackground(new java.awt.Color(243, 244, 246));
        PContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PContraseñaMouseClicked(evt);
            }
        });

        ejemplocontraseña.setBackground(new java.awt.Color(243, 244, 246));
        ejemplocontraseña.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ejemplocontraseña.setForeground(new java.awt.Color(204, 204, 204));
        ejemplocontraseña.setText("........");
        ejemplocontraseña.setBorder(null);
        ejemplocontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ejemplocontraseñaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ejemplocontraseñaMousePressed(evt);
            }
        });
        ejemplocontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplocontraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PContraseñaLayout = new javax.swing.GroupLayout(PContraseña);
        PContraseña.setLayout(PContraseñaLayout);
        PContraseñaLayout.setHorizontalGroup(
            PContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ejemplocontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        PContraseñaLayout.setVerticalGroup(
            PContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PContraseñaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ejemplocontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        PInicio.add(PContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, 30));

        PBoton.setBackground(new java.awt.Color(0, 189, 214));
        PBoton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        boton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton.setText("Ingresar");
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMouseExited(evt);
            }
        });
        PBoton.add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        PInicio.add(PBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 38));

        contraseña.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        contraseña.setText("contraseña");
        PInicio.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 110, 30));

        usuario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        usuario.setText("Usuario");
        PInicio.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 30));

        DatosNo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        DatosNo.setForeground(new java.awt.Color(255, 0, 0));
        PInicio.add(DatosNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 232, 170, -1));

        login.add(PInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 410, 430));

        PLogo.setBackground(new java.awt.Color(106, 138, 235));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IMG-20241009-WA0018.jpg"))); // NOI18N

        javax.swing.GroupLayout PLogoLayout = new javax.swing.GroupLayout(PLogo);
        PLogo.setLayout(PLogoLayout);
        PLogoLayout.setHorizontalGroup(
            PLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PLogoLayout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PLogoLayout.setVerticalGroup(
            PLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, Short.MAX_VALUE)
        );

        login.add(PLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 410, 430));

        Fondo_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/IMG-20241009-WA0028.jpg"))); // NOI18N
        login.add(Fondo_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1200, 720));

        Escritorio.setBackground(new java.awt.Color(63, 108, 229));
        Escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(51, 153, 255));

        jLabel10.setText("APP 5");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 340, Short.MAX_VALUE))
        );

        Escritorio.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 280, 410));

        OPERA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/opera.png"))); // NOI18N
        OPERA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OPERAMouseClicked(evt);
            }
        });
        Escritorio.add(OPERA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 70));

        PAPELERA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Excel.png"))); // NOI18N
        PAPELERA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAPELERAMouseClicked(evt);
            }
        });
        Escritorio.add(PAPELERA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, 70));

        jLabel6.setText("APP 1");
        Escritorio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 70, 70));

        jLabel8.setText("APP 3");
        Escritorio.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, 70));

        jLabel5.setText("APP 2");
        Escritorio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 70, 70));

        Barra_Tareas.setBackground(new java.awt.Color(51, 153, 255));
        Barra_Tareas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("inicio");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Barra_Tareas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 60));

        FECHA.setText("fecha ");
        Barra_Tareas.add(FECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 90, 40));

        jLabel3.setText("tareas activas");
        Barra_Tareas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 22, 104, -1));

        jLabel4.setText("Accesos rapidos");
        Barra_Tareas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 220, 60));

        HORA.setText("Hora");
        Barra_Tareas.add(HORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, 80, 30));

        Escritorio.add(Barra_Tareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1200, 70));

        Fondo_Escritorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo_Escritorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Fondo1.png"))); // NOI18N
        Fondo_Escritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fondo_EscritorioMouseClicked(evt);
            }
        });
        Escritorio.add(Fondo_Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 690));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Escritorio.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 640));

        getContentPane().add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void mostrar_fecha(){
        
        FECHA.setText(fechaHora.Fecha);
        HORA.setText(fechaHora.Hora);
    }
    public void ajustarImagen(JLabel label) {
    int labelWidth = label.getWidth();
    int labelHeight = label.getHeight();
    ImageIcon currentImageIcon = (ImageIcon) label.getIcon();
    if (currentImageIcon != null) {
        Image scaledImage = currentImageIcon.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        label.setIcon(scaledImageIcon);
    }
}

    private void botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseExited
        PBoton.setBackground(new Color(0, 189, 214));
    }//GEN-LAST:event_botonMouseExited

    private void botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseEntered
        PBoton.setBackground(new Color(20, 200, 230));
    }//GEN-LAST:event_botonMouseEntered

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
        String usuario = ejemplo.getText();
        String contraseña = String.valueOf(ejemplocontraseña.getPassword());
        if(usuario.equals(user) && contraseña.equals(pass)){
            Escritorio.setVisible(true);
            login.setVisible(false);
        }else {
            System.out.println("no puedes ingresar");
        }
        
    }//GEN-LAST:event_botonMouseClicked

    private void PContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PContraseñaMouseClicked

    }//GEN-LAST:event_PContraseñaMouseClicked

    private void ejemplocontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplocontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejemplocontraseñaActionPerformed

    private void ejemplocontraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejemplocontraseñaMousePressed
        if (String.valueOf(ejemplocontraseña.getPassword()).equals("........")) {
            ejemplocontraseña.setText("");
            ejemplocontraseña.setForeground(Color.BLACK);
        }
        if (ejemplo.getText().isEmpty()) {
            ejemplo.setText("ejemplo.gmail.com");
            ejemplo.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_ejemplocontraseñaMousePressed

    private void ejemplocontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejemplocontraseñaMouseClicked
        PContraseña.setBorder(new LineBorder(Color.WHITE));
    }//GEN-LAST:event_ejemplocontraseñaMouseClicked

    private void ejemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemploActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejemploActionPerformed

    private void ejemploMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejemploMousePressed
        if (ejemplo.getText().equals("ejemplo.gmail.com")) {
            ejemplo.setText("");
            ejemplo.setForeground(Color.BLACK);
        }
        if (String.valueOf(ejemplocontraseña.getPassword()).isEmpty()) {
            ejemplocontraseña.setText("........");
            ejemplocontraseña.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_ejemploMousePressed

    private void ejemploMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejemploMouseClicked
        PUsuario.setBorder(new LineBorder(Color.WHITE));
    }//GEN-LAST:event_ejemploMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       Menu.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void Fondo_EscritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fondo_EscritorioMouseClicked
        Menu.setVisible(false);
    }//GEN-LAST:event_Fondo_EscritorioMouseClicked

    private void PAPELERAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAPELERAMouseClicked
        Abrir_excel abrirExcel = new Abrir_excel();
            try {
                abrirExcel.abrir_Excel();
            } catch (IOException ex) {
                ex.printStackTrace();
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_PAPELERAMouseClicked

    private void OPERAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OPERAMouseClicked
        Abrir_opera abrirOpera = new Abrir_opera();
            try {
                abrirOpera.abrir_Opera();
            } catch (IOException ex) {
                ex.printStackTrace();
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_OPERAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cosmos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra_Tareas;
    private javax.swing.JLabel DatosNo;
    private javax.swing.JPanel Escritorio;
    private javax.swing.JLabel FECHA;
    private javax.swing.JLabel Fondo_Escritorio;
    private javax.swing.JLabel Fondo_Login;
    private javax.swing.JLabel HORA;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel OPERA;
    private javax.swing.JLabel PAPELERA;
    private javax.swing.JPanel PBoton;
    private javax.swing.JPanel PContraseña;
    private javax.swing.JPanel PInicio;
    private javax.swing.JPanel PLogo;
    private javax.swing.JPanel PUsuario;
    private javax.swing.JLabel boton;
    private javax.swing.JLabel contraseña;
    private javax.swing.JTextField ejemplo;
    private javax.swing.JPasswordField ejemplocontraseña;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel login;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
